name: l5b_amarel_neuron
channels:
  - conda-forge
dependencies:
  - python=3.12.*
  - neuron=8.2.*
  - numpy=1.26.*
  - pandas=3.0.*
  - scipy=1.17.*
  - networkx=3.6.*
  - matplotlib=3.11.*
  - biopython=1.87.*
  - tqdm=4.68.*
